name: build

on: [push, pull_request]

jobs:
  build_ubuntu:
    name: Build Stellarium Web Engine on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emsdk-version: [1.40.1, latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Setup Emscripten
        run: |
          # https://emscripten.org/docs/getting_started/downloads.html
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk/
          ./emsdk install ${{ matrix.emsdk-version }}
          ./emsdk activate ${{ matrix.emsdk-version }}
          # source ./emsdk_env.sh
      - name: Run Setup SConstruct
        run: |
          # https://scons.org/doc/production/HTML/scons-user/ch01s02.html
          python -m pip install scons
      - name: Run Make
        run: |
          #
          ls
          source ./emsdk/emsdk_env.sh
          make js

  build_macos:
    name: Build Stellarium Web Engine on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        emsdk-version: [1.40.1, latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Setup Emscripten
        run: |
          # https://emscripten.org/docs/getting_started/downloads.html
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk/
          ./emsdk install ${{ matrix.emsdk-version }}
          ./emsdk activate ${{ matrix.emsdk-version }}
          # source ./emsdk_env.sh
      - name: Run Setup SConstruct
        run: |
          # https://scons.org/doc/production/HTML/scons-user/ch01s02.html
          python -m pip install scons
      - name: Run Make
        run: |
          #
          ls
          source ./emsdk/emsdk_env.sh
          make js
